'''
Arithmétique alphabétique 
Posons A=1, B=2, C=3, etc. Pour un mot donné, on additionne le score de chaque lettre. Exemple : ABC = 6. Trouver la station de métro du 13e arrondissement dont le compte vaut 99.

Chevaleret : 3+8+5+22+1+12+5+18+5+20
 

h = {chr(i): i - 96 for i in range(ord('a'), ord('z') + 1)}
x = sum([h[c] for c in "chevaleret"])
print(x)

Le chiffre de César
Rechercher ce qu’est le chiffre de César.
Chiffrer à la main la phrase “BONJOUR MONDE”.
Déchiffrer à la main la phrase “DWWDTXHUDOHVLDPDLQWHQDQW”.
Implémenter le chiffrement/déchiffrement.
César utilisait un décallage de 3. Le texte suivant qui utilise un décallage inconnu :

XQOTURRDQPQOEMDRAZOFUAZZQBMDPOMXMSQPQEXQFFDQEPQXMXBTMNQFBMDQJQYBXQPMZEXUYMSQOUPQEEGEUXKMGZQPUEFMZOQPQOMDMOFDQEPAZONPQHUQZFQPMZEXQFQJFQOAPQZODKBFASDMBTUQXQOTURRDQYQZFBMDPOMXMSQMGEEUOAZZGOAYYQXQOTURRDQPQOEMDAGXQOAPQPQOEMDHAUDXQEPURRDQZFEZAYEQEFGZQYFTAPQPQOTURRDQYQZFFDEEUYBXQGFUXUEQBMDVGXQEOEMDPMZEEQEOADDQEBAZPMZOQEEQODFQEOQCGUQJBXUCGQXQZAYOTURRDQPQOEMDXQFQJFQOTURRDEANFUQZFQZDQYBXMMZFOTMCGQXQFFDQPGFQJFQOXMUDADUSUZMXBMDGZQXQFFDQPUEFMZOQRUJQFAGVAGDEPGYYQOFPMZEXADPDQPQXMXBTMNQFBAGDXQEPQDZUDQEXQFFDQEPMZEXQOMEPGZPOMXMSQPDAUFQAZDQBDQZPMGPNGFBMDQJQYBXQMHQOGZPOMXMSQPQHQDEXMPDAUFQMQEFDQYBXMOBMDPNPQHUQZFQQFMUZEUVGECGICGUPQHUQZFLBGUEJPQHUQZFMQFOUXEMSUFPGZQBQDYGFMFUAZOUDOGXMUDQPQXMXBTMNQFXMXAZSGQGDPGPOMXMSQPMZEXQJQYBXQHACGOAZEFUFGQXMOXPGOTURRDQYQZFCGUXEGRRUFPQFDMZEYQFFDQMGPQEFUZMFMUDQEUXEMUFPVCGUXEMSUFPGZOTURRDQYQZFPQOEMDBAGDCGQOQXGUOUBGUEEQPOTURRDQDXQYQEEMSQPMZEXQOMEPQXMXBTMNQFXMFUZXQOTURRDQPQOEMDZMCGQOXEBAEEUNXQEKOAYBDUEXMOXZGXXQCGUZQYAPURUQBMEXQFQJFQUXEMSUFPGZOMEBMDFUOGXUQDPQOTURRDQYQZFBMDEGNEFUFGFUAZYAZAMXBTMNFUCGQOQEEGNEFUFGFUAZEDQBAEQZFEGDGZBDUZOUBQMZMXASGQYMUEEAZFANFQZGQEBMDPQEBQDYGFMFUAZECGQXOAZCGQEPQEXQFFDQEPQXMXBTMNQFPMZEXQOMESZDMXXMOXQEFPAZZQBMDXMBQDYGFMFUAZQFXQZAYNDQPQOXEBAEEUNXQEQEFMXADEEMZEOAYYGZQYQEGDQMHQOOQXGUPQEOTURRDQYQZFEPQOEMDXQOTURRDQYQZFPQOEMDMBGFDQGFUXUEOAYYQXYQZFPGZQYFTAPQBXGEOAYBXQJQOAYYQXQOTURRDQPQHUSQZDQEQGXUXZARRDQMGOGZQEOGDUFPQOAYYGZUOMFUAZOMGEQPGFDERMUNXQZAYNDQPQOXEOQCGUBQDYQFPQEEMKQDEKEFYMFUCGQYQZFOQXXQEOUCGMZPXMYFTAPQPQOTURRDQYQZFQEFOAZZGQYMUEMGEEUBMDOQCGQOAYYQFAGFQZOAPMSQBMDEGNEFUFGFUAZYAZAMXBTMNFUCGQUXBQGFFDQFDEDMBUPQYQZFOMEEBMDMZMXKEQPQRDCGQZOQEOQDFMUZQEXQFFDQEMBBMDMUEEQZFNQMGOAGBBXGEEAGHQZFCGQXQEMGFDQEPMZEGZQXMZSGQZMFGDQXXQ

Tester les 26 possibilités pour déchiffrer le texte.
En français, la répartition des lettres est inégale. Par exemple, la lettre “e” apparaît plus fréquemment que toutes les autres lettres. Calculer la répartition de chacune des lettres dans le texte. Quelles lettres arrive en tête ? Pouvez-vous en déduire le décallage ?
'''

'''
minuscules = 'abcdefghijklmnopqrstuvwxyz'
majuscules = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

def rotation(chaine, x):
    """
     Effectue une rotation de x caractères vers la droite:
     >>> rotation('abcde', 2)
     'cdeab'
    """
    return chaine[x:] + chaine[:x]

def index(c, chaine):
    """
     Trouve l'index de c dans la chaine:
     >>> index('n', 'bonjour')
     2
    """
    for i in range(len(chaine)):
        if (c == chaine[i]):
            return i
    return -1

def chiffre_minuscules(chaine, x):
    """
     Chiffre une chaîne composée de minuscules
     >>> chiffre_minuscules('bonjour', 3)
     'erqmrxu'
    """
    r = rotation(minuscules, x)
    resultat = ''
    for lettre in chaine:
        resultat = resultat + r[index(lettre, minuscules)]
    return resultat

def chiffre(chaine, x):
    """
     Chiffre une chaîne quelconque
     >>> chiffre('Bonjour les amis!', 3)
     'Erqmrxu ohv dplv!'
    """
    r_min = rotation(minuscules, x)
    r_maj = rotation(majuscules, x)
    resultat = ''
    for lettre in chaine:
        if lettre in minuscules:
            resultat = resultat + r_min[index(lettre, minuscules)]
        elif lettre in majuscules:
            resultat = resultat + r_maj[index(lettre, majuscules)]
        else:
            resultat = resultat + lettre
    return resultat

print(chiffre_minuscules('bonjour', 3))
print(chiffre('Bonjour les amis!', 3))
print(chiffre('Erqmrxu ohv dplv!', 23))
print(chiffre('DWWDTXHUDOHVLDPDLQWHQDQW',3))

print(chiffre('XQOTURRDQPQOEMDRAZOFUAZZQBMDPOMXMSQPQEXQFFDQEPQXMXBTMNQFBMDQJQYBXQPMZEXUYMSQOUPQEEGEUXKMGZQPUEFMZOQPQOMDMOFDQEPAZONPQHUQZFQPMZEXQFQJFQOAPQZODKBFASDMBTUQXQOTURRDQYQZFBMDPOMXMSQMGEEUOAZZGOAYYQXQOTURRDQPQOEMDAGXQOAPQPQOEMDHAUDXQEPURRDQZFEZAYEQEFGZQYFTAPQPQOTURRDQYQZFFDEEUYBXQGFUXUEQBMDVGXQEOEMDPMZEEQEOADDQEBAZPMZOQEEQODFQEOQCGUQJBXUCGQXQZAYOTURRDQPQOEMDXQFQJFQOTURRDEANFUQZFQZDQYBXMMZFOTMCGQXQFFDQPGFQJFQOXMUDADUSUZMXBMDGZQXQFFDQPUEFMZOQRUJQFAGVAGDEPGYYQOFPMZEXADPDQPQXMXBTMNQFBAGDXQEPQDZUDQEXQFFDQEPMZEXQOMEPGZPOMXMSQPDAUFQAZDQBDQZPMGPNGFBMDQJQYBXQMHQOGZPOMXMSQPQHQDEXMPDAUFQMQEFDQYBXMOBMDPNPQHUQZFQQFMUZEUVGECGICGUPQHUQZFLBGUEJPQHUQZFMQFOUXEMSUFPGZQBQDYGFMFUAZOUDOGXMUDQPQXMXBTMNQFXMXAZSGQGDPGPOMXMSQPMZEXQJQYBXQHACGOAZEFUFGQXMOXPGOTURRDQYQZFCGUXEGRRUFPQFDMZEYQFFDQMGPQEFUZMFMUDQEUXEMUFPVCGUXEMSUFPGZOTURRDQYQZFPQOEMDBAGDCGQOQXGUOUBGUEEQPOTURRDQDXQYQEEMSQPMZEXQOMEPQXMXBTMNQFXMFUZXQOTURRDQPQOEMDZMCGQOXEBAEEUNXQEKOAYBDUEXMOXZGXXQCGUZQYAPURUQBMEXQFQJFQUXEMSUFPGZOMEBMDFUOGXUQDPQOTURRDQYQZFBMDEGNEFUFGFUAZYAZAMXBTMNFUCGQOQEEGNEFUFGFUAZEDQBAEQZFEGDGZBDUZOUBQMZMXASGQYMUEEAZFANFQZGQEBMDPQEBQDYGFMFUAZECGQXOAZCGQEPQEXQFFDQEPQXMXBTMNQFPMZEXQOMESZDMXXMOXQEFPAZZQBMDXMBQDYGFMFUAZQFXQZAYNDQPQOXEBAEEUNXQEQEFMXADEEMZEOAYYGZQYQEGDQMHQOOQXGUPQEOTURRDQYQZFEPQOEMDXQOTURRDQYQZFPQOEMDMBGFDQGFUXUEOAYYQXYQZFPGZQYFTAPQBXGEOAYBXQJQOAYYQXQOTURRDQPQHUSQZDQEQGXUXZARRDQMGOGZQEOGDUFPQOAYYGZUOMFUAZOMGEQPGFDERMUNXQZAYNDQPQOXEOQCGUBQDYQFPQEEMKQDEKEFYMFUCGQYQZFOQXXQEOUCGMZPXMYFTAPQPQOTURRDQYQZFQEFOAZZGQYMUEMGEEUBMDOQCGQOAYYQFAGFQZOAPMSQBMDEGNEFUFGFUAZYAZAMXBTMNFUCGQUXBQGFFDQFDEDMBUPQYQZFOMEEBMDMZMXKEQPQRDCGQZOQEOQDFMUZQEXQFFDQEMBBMDMUEEQZFNQMGOAGBBXGEEAGHQZFCGQXQEMGFDQEPMZEGZQXMZSGQZMFGDQXXQ',14))


from collections import Counter
c = Counter("XQOTURRDQPQOEMDRAZOFUAZZQBMDPOMXMSQPQEXQFFDQEPQXMXBTMNQFBMDQJQYBXQPMZEXUYMSQOUPQEEGEUXKMGZQPUEFMZOQPQOMDMOFDQEPAZONPQHUQZFQPMZEXQFQJFQOAPQZODKBFASDMBTUQXQOTURRDQYQZFBMDPOMXMSQMGEEUOAZZGOAYYQXQOTURRDQPQOEMDAGXQOAPQPQOEMDHAUDXQEPURRDQZFEZAYEQEFGZQYFTAPQPQOTURRDQYQZFFDEEUYBXQGFUXUEQBMDVGXQEOEMDPMZEEQEOADDQEBAZPMZOQEEQODFQEOQCGUQJBXUCGQXQZAYOTURRDQPQOEMDXQFQJFQOTURRDEANFUQZFQZDQYBXMMZFOTMCGQXQFFDQPGFQJFQOXMUDADUSUZMXBMDGZQXQFFDQPUEFMZOQRUJQFAGVAGDEPGYYQOFPMZEXADPDQPQXMXBTMNQFBAGDXQEPQDZUDQEXQFFDQEPMZEXQOMEPGZPOMXMSQPDAUFQAZDQBDQZPMGPNGFBMDQJQYBXQMHQOGZPOMXMSQPQHQDEXMPDAUFQMQEFDQYBXMOBMDPNPQHUQZFQQFMUZEUVGECGICGUPQHUQZFLBGUEJPQHUQZFMQFOUXEMSUFPGZQBQDYGFMFUAZOUDOGXMUDQPQXMXBTMNQFXMXAZSGQGDPGPOMXMSQPMZEXQJQYBXQHACGOAZEFUFGQXMOXPGOTURRDQYQZFCGUXEGRRUFPQFDMZEYQFFDQMGPQEFUZMFMUDQEUXEMUFPVCGUXEMSUFPGZOTURRDQYQZFPQOEMDBAGDCGQOQXGUOUBGUEEQPOTURRDQDXQYQEEMSQPMZEXQOMEPQXMXBTMNQFXMFUZXQOTURRDQPQOEMDZMCGQOXEBAEEUNXQEKOAYBDUEXMOXZGXXQCGUZQYAPURUQBMEXQFQJFQUXEMSUFPGZOMEBMDFUOGXUQDPQOTURRDQYQZFBMDEGNEFUFGFUAZYAZAMXBTMNFUCGQOQEEGNEFUFGFUAZEDQBAEQZFEGDGZBDUZOUBQMZMXASGQYMUEEAZFANFQZGQEBMDPQEBQDYGFMFUAZECGQXOAZCGQEPQEXQFFDQEPQXMXBTMNQFPMZEXQOMESZDMXXMOXQEFPAZZQBMDXMBQDYGFMFUAZQFXQZAYNDQPQOXEBAEEUNXQEQEFMXADEEMZEOAYYGZQYQEGDQMHQOOQXGUPQEOTURRDQYQZFEPQOEMDXQOTURRDQYQZFPQOEMDMBGFDQGFUXUEOAYYQXYQZFPGZQYFTAPQBXGEOAYBXQJQOAYYQXQOTURRDQPQHUSQZDQEQGXUXZARRDQMGOGZQEOGDUFPQOAYYGZUOMFUAZOMGEQPGFDERMUNXQZAYNDQPQOXEOQCGUBQDYQFPQEEMKQDEKEFYMFUCGQYQZFOQXXQEOUCGMZPXMYFTAPQPQOTURRDQYQZFQEFOAZZGQYMUEMGEEUBMDOQCGQOAYYQFAGFQZOAPMSQBMDEGNEFUFGFUAZYAZAMXBTMNFUCGQUXBQGFFDQFDEDMBUPQYQZFOMEEBMDMZMXKEQPQRDCGQZOQEOQDFMUZQEXQFFDQEMBBMDMUEEQZFNQMGOAGBBXGEEAGHQZFCGQXQEMGFDQEPMZEGZQXMZSGQZMFGDQXXQ")
#Counter({'e': 2, 'u': 1, 'a': 1, ' ': 1, 's': 1, 'r': 1, 'n': 1, 'h': 1, 'p': 1})
print(c)
'''

'''
#Generer un nombre de maniere aleatoire : 

import random
charlie = random.randint(0, 100)
vies = 6
appreciation = "?"
while vies > 0:
    maurice = int (input("Donnes moi ton nombre: "))
    maurice = int(maurice)
    if maurice < charlie :
        appreciation = "Il est plus grand !"
        print(vies, maurice, appreciation)
    elif charlie == maurice: 
        print ('Bravo!')
    else :
        appreciation = " Il est plus petit"
        print(vies, maurice, appreciation)
        break       
    vies -= 1

'''

# Calcul de l'IMC :

def imc (masse, taille):
    return masse/(taille**2)

masse_utilisateur = int(input("Entrez votre poids en kg:"))
taille_utilisateur = float(input("Entrez votre taille en m : "))
imc = imc(masse_utilisateur, taille_utilisateur)
 
if imc > 25.0:
    print("Vous êtes en surpoids.")
elif imc < 18.5:
    print("Vous êtes trop maigre.")
else:
    print("Vous avez une corpulence normale.")
